version: "3.5"

services:
  front-end:
    container_name: front-end
    build: ./
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "8085:8085"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
